# Generated by Django 5.2.7 on 2025-10-12 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBreachCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('breaches_found', models.IntegerField(default=0)),
                ('breach_details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ssl_valid', models.BooleanField(default=False)),
                ('ssl_issuer', models.CharField(blank=True, max_length=200)),
                ('ssl_expiry', models.DateTimeField(blank=True, null=True)),
                ('ssl_grade', models.CharField(blank=True, max_length=10)),
                ('has_hsts', models.BooleanField(default=False)),
                ('has_csp', models.BooleanField(default=False)),
                ('has_xframe', models.BooleanField(default=False)),
                ('has_xss_protection', models.BooleanField(default=False)),
                ('has_content_type', models.BooleanField(default=False)),
                ('cms_detected', models.CharField(blank=True, max_length=100)),
                ('cms_version', models.CharField(blank=True, max_length=50)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('security_score', models.IntegerField(default=0)),
                ('grade', models.CharField(default='F', max_length=2)),
                ('server_info', models.CharField(blank=True, max_length=200)),
                ('technologies', models.TextField(blank=True)),
                ('vulnerabilities', models.TextField(blank=True)),
            ],
        ),
    ]
