# Generated by Django 4.2.25 on 2025-10-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_advancedsecurityscan_scanconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityfinding',
            options={'ordering': ['-cvss_score', '-created_date']},
        ),
    ]
